query FetchPerson($id: UUID!) {
	person: account(id: $id) {
		id
		name
		publishedProjects {
			id
			title
			status
		}
	}
}

query FetchDrafts($userId: UUID!) {
	projects(condition: {ownerId: $userId, status: DRAFT}) {
		nodes {
			id
			title
		}
	}
}

query FetchDraft($draftId: UUID!, $userId: UUID!) {
	project(id: $draftId, ownerId: $userId, status: DRAFT) {
		id
		title
		body
		initialAmount
		monthCount
		monthlyAmount
		prizeAmount
	}
}

mutation CreateDraft($input: CreateNewDraftInput!) {
	createNewDraft(input: $input) {
		uuid
	}
}

mutation SaveDraft(
	$projectId: UUID!, $title: String!, $body: String!,
	$initialAmount: BigFloat!, $monthCount: BigFloat!, $monthlyAmount: BigFloat!, $prizeAmount: BigFloat!,
) {
	updateProject(
		input: {id: $projectId, patch: {
			title: $title,
			body: $body,
			initialAmount: $initialAmount,
			monthCount: $monthCount,
			monthlyAmount: $monthlyAmount,
			prizeAmount: $prizeAmount,
		}}
	)
}

mutation PublishDraft($projectId: UUID!) {
	publishDraft(input: {projectId: $projectId})
}

# mutation UnpublishDraft($projectId: UUID!) {
# 	unpublishProject(input: {projectId: $projectId})
# }


query FetchProposals {
	projects(condition: {status: PROPOSAL}) {
		nodes {
			id
			owner {
				id
				name
			}
			title
			overallPledgedAmount
			fundingRequirement
		}
	}
}


query FetchProposal($proposalId: UUID!) {
	project(id: $proposalId, status: PROPOSAL) {
		id
		owner {
			id
			name
		}
		title
		body
		initialAmount
		monthCount
		monthlyAmount
		prizeAmount
		# baseFundingRequirement
		fundingRequirement
		overallPledgedAmount
		overallPledgerCount
	}
}


mutation MakePledge($pledgerId: UUID!, $projectId: UUID!, $amount: BigFloat!) {
	makePledge(
		input: {pledgerId: $pledgerId, projectId: $projectId, amount: $amount}
	)
}

query FetchProject($projectId: UUID!, $userId: UUID!) {
	project(id: $projectId) {
		id
		owner {
			id
			name
		}
		title
		body
		status
		initialAmount
		monthCount
		monthlyAmount
		prizeAmount

		# baseFundingRequirement
		fundingRequirement
		actualPrizeAmount
		totalPledgedAmount
		totalPledgerCount

		fundsPaid
		monthsPassed
		nextPayment {
			amount
			isLast
			kind
		}
		overallPledgeVote {
			shouldContinue
			weightInFavor
			weightOpposed
		}

		userPledge(userId: $userId) {
			vote
			amount
			count
		}
	}
}

mutation CastVote($pledgerId: UUID!, $projectId: UUID!, $shouldContinue: Boolean!) {
	castVote(
		input: {argPledgerId: $pledgerId, argProjectId: $projectId, argShouldContinue: $shouldContinue}
	)
}


query FetchProjects {
	projects {
		nodes {
			id
			owner {
				id
				name
			}
			title
			totalPledgedAmount
			monthsPassed
			monthCount
			fundsPaid
		}
	}
}
