query UserDrafts($userId: UUID!) {
	rawProposals(condition: {status: DRAFT, ownerId: $userId}) {
		nodes {
			id
			title
		}
	}
}

query UserDraft($userId: UUID!) {
	rawProposals(condition: {status: DRAFT, ownerId: $userId}) {
		nodes {
			id
			title
			prizeAmount
			months
		}
	}
}

mutation CreateDraft($ownerId: UUID!, $title: String!) {
	#
}
